CREATE TABLE RM_USER_INFO (
                              USER_INFO_ID INT(11) NOT NULL AUTO_INCREMENT
    , USER_LOGIN_ID VARCHAR(50) NOT NULL
    , FIRST_NAME VARCHAR(100) NOT NULL
    , MIDDLE_NAME VARCHAR(100) NOT NULL
    , LAST_NAME VARCHAR(100) NOT NULL
    , USER_PHONE INT(10) NOT NULL
    , USER_PHONE_VERIFIED tinyint(1) NOT NULL DEFAULT 0
    , USER_EMAIL VARCHAR(200) NOT NULL
    , USER_EMAIL_VERIFIED tinyint(1) NOT NULL DEFAULT 0
    , CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    , CREATED_BY      VARCHAR(50) NOT NULL
    , UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    , UPDATED_BY      VARCHAR(50) NOT NULL
    , CONSTRAINT RT_USER_INFO_PK PRIMARY KEY (USER_INFO_ID)
);

CREATE TABLE RM_ACCOUNT_TYPE (
                                 ACCOUNT_TYPE_ID INT(50) NOT NULL
    , ACCOUNT_TYPE_DESC VARCHAR(100) NOT NULL
    , CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    , CREATED_BY      VARCHAR(50) NOT NULL
    , UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    , UPDATED_BY      VARCHAR(50) NOT NULL
    , CONSTRAINT RM_ACCOUNT_TYPE_PK PRIMARY KEY (ACCOUNT_TYPE_ID)
);

CREATE TABLE RM_ACCOUNT (
                            ACCOUNT_ID INT(11) NOT NULL AUTO_INCREMENT
    , MONEY_ACCOUNT_ID VARCHAR(100) NOT NULL
    , ACCOUNT_TYPE_ID INT(50) NOT NULL
    , MONEY_ACCOUNT_BALANCE DECIMAL(19,4) NOT NULL DEFAULT '0.00'
    , CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    , CREATED_BY      VARCHAR(50) NOT NULL
    , UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    , UPDATED_BY      VARCHAR(50) NOT NULL
    , CONSTRAINT RM_ACCOUNT_PK PRIMARY KEY (ACCOUNT_ID)
    , CONSTRAINT RM_ACCOUNT_FK1 FOREIGN KEY (ACCOUNT_TYPE_ID) REFERENCES RM_ACCOUNT_TYPE (ACCOUNT_TYPE_ID)
);

CREATE TABLE RM_USER_ACCOUNT (
                                 USER_ACCOUNT_ID INT(11) NOT NULL AUTO_INCREMENT
    , USER_INFO_ID INT(11) NOT NULL
    , ACCOUNT_ID INT(11) NOT NULL
    , CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    , CREATED_BY      VARCHAR(50) NOT NULL
    , UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    , UPDATED_BY      VARCHAR(50) NOT NULL
    , CONSTRAINT RM_USER_ACCOUNT_PK PRIMARY KEY (USER_ACCOUNT_ID)
    , CONSTRAINT RM_USER_ACCOUNT_FK1 FOREIGN KEY (USER_INFO_ID) REFERENCES RM_USER_INFO (USER_INFO_ID)
    , CONSTRAINT RM_USER_ACCOUNT_FK2 FOREIGN KEY (ACCOUNT_ID) REFERENCES RM_ACCOUNT (ACCOUNT_ID)
);

CREATE TABLE RM_TRANSACTION_TYPE (
                                     TRANSACTION_TYPE_CODE CHAR(1) NOT NULL
    , TRANSACTION_TYPE_CODE_DESC VARCHAR(100) NOT NULL
    , CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    , CREATED_BY      VARCHAR(50) NOT NULL
    , UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    , UPDATED_BY      VARCHAR(50) NOT NULL
    , CONSTRAINT RM_TRANSACTION_TYPE_PK PRIMARY KEY (TRANSACTION_TYPE_CODE)
);

CREATE TABLE RT_TRANSACTION (
                                TRANSACTION_ID INT(11) NOT NULL AUTO_INCREMENT
    , TRANSACTION_UNIQUE_ID VARCHAR(100) NOT NULL
    , TRANSACTION_TYPE_CODE CHAR(1) NOT NULL
    , TRANSACTION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    , TRANSACTION_AMOUNT DECIMAL(19,4) NOT NULL
    , CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    , CREATED_BY      VARCHAR(50) NOT NULL
    , UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    , UPDATED_BY      VARCHAR(50) NOT NULL
    , CONSTRAINT RT_TRANSACTION_PK PRIMARY KEY (TRANSACTION_ID)
    , CONSTRAINT RT_TRANSACTION_FK1 FOREIGN KEY (TRANSACTION_TYPE_CODE) REFERENCES RM_TRANSACTION_TYPE(TRANSACTION_TYPE_CODE)
);

CREATE TABLE RT_TRANSACTION_LEDGER (
                                       TRANSACTION_LEDGER_ID INT(11) NOT NULL AUTO_INCREMENT
    , TRANSACTION_ID INT(11) NOT NULL
    , ACCOUNT_ID INT(11) NOT NULL
    , LEDGER_TYPE_CODE CHAR(1) NOT NULL
    , LEDGER_TRANSACTION_AMOUNT DECIMAL(19,4) NOT NULL
    , CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    , CREATED_BY      VARCHAR(50) NOT NULL
    , UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    , UPDATED_BY      VARCHAR(50) NOT NULL
    , CONSTRAINT RT_TRANSACTION_LEDGER_PK PRIMARY KEY (TRANSACTION_LEDGER_ID)
    , CONSTRAINT RT_TRANSACTION_LEDGER_FK1 FOREIGN KEY (TRANSACTION_ID) REFERENCES RT_TRANSACTION(TRANSACTION_ID)
    , CONSTRAINT RT_TRANSACTION_LEDGER_FK2 FOREIGN KEY (ACCOUNT_ID) REFERENCES RM_ACCOUNT(ACCOUNT_ID)
);