INSERT INTO RM_ACCOUNT_TYPE(ACCOUNT_TYPE_ID,ACCOUNT_TYPE_DESC,CREATED_BY,UPDATED_BY)
values (0,"cash",'Admin','Admin');

INSERT INTO RM_ACCOUNT (MONEY_ACCOUNT_ID,ACCOUNT_TYPE_ID,MONEY_ACCOUNT_BALANCE,CREATED_BY,UPDATED_BY)
VALUES('accAnirudh',0,10000,'Admin','Admin');
INSERT INTO RM_ACCOUNT (MONEY_ACCOUNT_ID,ACCOUNT_TYPE_ID,MONEY_ACCOUNT_BALANCE,CREATED_BY,UPDATED_BY)
VALUES('accRakshith',0,10000,'Admin','Admin');
INSERT INTO RM_ACCOUNT (MONEY_ACCOUNT_ID,ACCOUNT_TYPE_ID,MONEY_ACCOUNT_BALANCE,CREATED_BY,UPDATED_BY)
VALUES('accNishanth',0,10000,'Admin','Admin');


INSERT into RM_USER_INFO(USER_LOGIN_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,USER_PHONE,USER_PHONE_VERIFIED,USER_EMAIL,USER_EMAIL_VERIFIED,CREATED_BY,UPDATED_BY)
VALUES('18891A05D6','Anirudh',' ','G',123456789,1,'nishanth@mail.com',1,'Admin','Admin');
INSERT into RM_USER_INFO(USER_LOGIN_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,USER_PHONE,USER_PHONE_VERIFIED,USER_EMAIL,USER_EMAIL_VERIFIED,CREATED_BY,UPDATED_BY)
VALUES('18891A05D5','Rakshith',' ','A',123456788,1,'nishanth@mail.com',1,'Admin','Admin');
INSERT into RM_USER_INFO(USER_LOGIN_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,USER_PHONE,USER_PHONE_VERIFIED,USER_EMAIL,USER_EMAIL_VERIFIED,CREATED_BY,UPDATED_BY)
VALUES('18891A05D0','Nishanth',' ','B',123456787,1,'nishanth@mail.com',1,'Admin','Admin');

INSERT INTO RM_USER_ACCOUNT(USER_INFO_ID,ACCOUNT_ID,CREATED_BY,UPDATED_BY)
VALUES(1,1,'Admin','Admin');
INSERT INTO RM_USER_ACCOUNT(USER_INFO_ID,ACCOUNT_ID,CREATED_BY,UPDATED_BY)
VALUES(2,2,'Admin','Admin');
INSERT INTO RM_USER_ACCOUNT(USER_INFO_ID,ACCOUNT_ID,CREATED_BY,UPDATED_BY)
VALUES(3,3,'Admin','Admin');

INSERT INTO RM_TRANSACTION_TYPE(TRANSACTION_TYPE_CODE,TRANSACTION_TYPE_CODE_DESC,CREATED_BY,UPDATED_BY)
values ('a','DEPOSIT','Admin','Admin');
INSERT INTO RM_TRANSACTION_TYPE(TRANSACTION_TYPE_CODE,TRANSACTION_TYPE_CODE_DESC,CREATED_BY,UPDATED_BY)
values ('b','TRANSFER','Admin','Admin');
INSERT INTO RM_TRANSACTION_TYPE(TRANSACTION_TYPE_CODE,TRANSACTION_TYPE_CODE_DESC,CREATED_BY,UPDATED_BY)
values ('c','WITHDRAWAL','Admin','Admin');